services:
  web:
    build:
      context: web
      args:
        - PUBLIC_PB_URL=${PUBLIC_PB_URL}
        - PB_EMAIL=${PB_EMAIL}
        - PB_PW=${PB_PW}
    env_file: .env    
    ports:
      - "4321:4321"

  pb:
    build: pb
    env_file: .env
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
    ports:
      - "8090:8090"

